server:
  port: ${SERVER_PORT:8080}

spring:
  sql: #
    init: #
    #  mode: always #
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    # defer-datasource-initialization: true #
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:create-drop} #create-drop #mandar para deploy mandar com UPDATE
      show-sql: true
  datasource:
    platform: postgres
    url: ${POSTGRES_URL:jdbc:postgresql://ec2-23-23-151-191.compute-1.amazonaws.com:5432/d7rnaolbfphe0n}
    username: ${POSTGRES_USER:vcairsauvnetnm}
    password: ${POSTGRES_PASSWORD:9bd86207e33ed95aac93cce30b5e9ea81ddba2ef0217ace4c30f6fd9fd985929}
    driverClassName: org.postgresql.Driver